# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdminWindow(object):
    def setupUi(self, AdminWindow):
        AdminWindow.setObjectName("AdminWindow")
        AdminWindow.resize(1004, 696)
        self.centralwidget = QtWidgets.QWidget(AdminWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox_tables = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_tables.setGeometry(QtCore.QRect(30, 20, 551, 22))
        self.comboBox_tables.setObjectName("comboBox_tables")
        self.pushButton_add = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add.setGeometry(QtCore.QRect(630, 10, 161, 31))
        self.pushButton_add.setObjectName("pushButton_add")
        self.pushButton_delete = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_delete.setGeometry(QtCore.QRect(810, 10, 161, 31))
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.lineEdit_searchQuery = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_searchQuery.setGeometry(QtCore.QRect(600, 70, 361, 21))
        self.lineEdit_searchQuery.setObjectName("lineEdit_searchQuery")
        self.comboBox_sortBy = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_sortBy.setGeometry(QtCore.QRect(30, 70, 301, 22))
        self.comboBox_sortBy.setObjectName("comboBox_sortBy")
        self.label_search = QtWidgets.QLabel(self.centralwidget)
        self.label_search.setGeometry(QtCore.QRect(30, 50, 71, 16))
        self.label_search.setText("")
        self.label_search.setObjectName("label_search")
        self.label_sort1 = QtWidgets.QLabel(self.centralwidget)
        self.label_sort1.setGeometry(QtCore.QRect(30, 50, 51, 16))
        self.label_sort1.setObjectName("label_sort1")
        self.label_sort2 = QtWidgets.QLabel(self.centralwidget)
        self.label_sort2.setGeometry(QtCore.QRect(350, 50, 81, 16))
        self.label_sort2.setObjectName("label_sort2")
        self.comboBox_searchColumn = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_searchColumn.setGeometry(QtCore.QRect(350, 70, 221, 22))
        self.comboBox_searchColumn.setObjectName("comboBox_searchColumn")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setEnabled(True)
        self.tableView.setGeometry(QtCore.QRect(30, 110, 941, 521))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        self.tableView.setSizePolicy(sizePolicy)
        self.tableView.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView.setGridStyle(QtCore.Qt.SolidLine)
        self.tableView.setSortingEnabled(True)
        self.tableView.setWordWrap(False)
        self.tableView.setCornerButtonEnabled(False)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setCascadingSectionResizes(True)
        self.tableView.horizontalHeader().setDefaultSectionSize(136)
        self.tableView.horizontalHeader().setSortIndicatorShown(True)
        self.tableView.horizontalHeader().setStretchLastSection(True)
        self.label_sort2_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_sort2_2.setGeometry(QtCore.QRect(600, 50, 81, 16))
        self.label_sort2_2.setObjectName("label_sort2_2")

        self.retranslateUi(AdminWindow)
        QtCore.QMetaObject.connectSlotsByName(AdminWindow)

    def retranslateUi(self, AdminWindow):
        _translate = QtCore.QCoreApplication.translate
        AdminWindow.setWindowTitle(_translate("AdminWindow", "MainWindow"))
        self.pushButton_add.setText(_translate("AdminWindow", "ADD"))
        self.pushButton_delete.setText(_translate("AdminWindow", "DELETE"))
        self.label_sort1.setText(_translate("AdminWindow", "Sort by"))
        self.label_sort2.setText(_translate("AdminWindow", "Seatch by column:"))
        self.label_sort2_2.setText(_translate("AdminWindow", "Search:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AdminWindow = QtWidgets.QMainWindow()
    ui = Ui_AdminWindow()
    ui.setupUi(AdminWindow)
    AdminWindow.show()
    sys.exit(app.exec_())
