# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trainer_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TrainerWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(773, 496)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_personal = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_personal.setGeometry(QtCore.QRect(10, 30, 231, 81))
        self.pushButton_personal.setObjectName("pushButton_personal")
        self.pushButton_animals = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_animals.setGeometry(QtCore.QRect(10, 130, 231, 81))
        self.pushButton_animals.setObjectName("pushButton_animals")
        self.pushButton_shows = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_shows.setGeometry(QtCore.QRect(10, 230, 231, 81))
        self.pushButton_shows.setObjectName("pushButton_shows")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(270, 20, 441, 421))
        self.tableView.setObjectName("tableView")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_personal.setText(_translate("MainWindow", "MOJE DANE"))
        self.pushButton_animals.setText(_translate("MainWindow", "MOJE ZWIERZĘTA"))
        self.pushButton_shows.setText(_translate("MainWindow", "MOJE POKAZY"))


